"""Application ports for source-data persistence and side effects."""

from __future__ import annotations

from collections.abc import Callable, Sequence
from datetime import datetime
from typing import Any, Protocol

from haoai_backend.shared.identity import TrustedActor

from .domain import ChapterRecord, SeriesRecord, StoryboardAssetRecord


class SeriesDataUnitOfWork(Protocol):
    def ensure_clean(self) -> None: ...
    def require_access(self, actor: TrustedActor, series_id: str) -> None: ...
    def load_series(self, series_id: str) -> SeriesRecord | None: ...
    def resolve_prompt(self, prompt_id: str | None) -> dict[str, Any] | None: ...
    def load_detail_names(self, record: SeriesRecord) -> tuple[str | None, str | None]: ...
    def list_series_for_actor(self, actor: TrustedActor) -> list[dict[str, Any]]: ...
    def create_series(self, actor: TrustedActor, values: dict[str, Any]) -> SeriesRecord: ...
    def update_series(self, series_id: str, values: dict[str, Any]) -> SeriesRecord: ...
    def delete_series(self, actor: TrustedActor, series_id: str) -> None: ...
    def list_chapters(self, series_id: str, actor: TrustedActor, now: datetime) -> list[dict[str, Any]]: ...
    def reorder_chapter(self, series_id: str, item: dict[str, Any]) -> None: ...
    def max_chapter_order(self, series_id: str) -> int | None: ...
    def create_chapter(self, series_id: str, title: str, content: list[dict[str, Any]], order: int) -> ChapterRecord: ...
    def load_chapter(self, chapter_id: str) -> ChapterRecord | None: ...
    def update_chapter_fields(self, chapter: ChapterRecord, values: dict[str, Any], actor: TrustedActor, now: datetime) -> ChapterRecord: ...
    def delete_frame_first_phase(self, chapter: ChapterRecord, actor: TrustedActor, frame_index: int, frames: list[Any]) -> ChapterRecord: ...
    def delete_chapter(self, chapter: ChapterRecord) -> tuple[str, dict[str, set[object]]]: ...
    def cleanup_orphans(self, series_id: str, refs: dict[str, set[object]]) -> None: ...
    def list_storyboard_assets(self, series_id: str, chapter_id: str | None) -> list[StoryboardAssetRecord]: ...
    def sync_storyboard_assets(self, chapter_id: str, series_id: str, *, final_content: object | None = None) -> ChapterRecord | None: ...
    def list_chat_messages(self, chapter_id: str) -> list[dict[str, Any]]: ...
    def update_chat_mapping(self, chapter_id: str, old_frames: list[Any], new_frames: list[Any]) -> None: ...
    def delete_chat_frame_and_shift(self, chapter_id: str, frame_index: int) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def is_integrity_error(self, error: BaseException) -> bool: ...


UnitOfWorkFactory = Callable[[], SeriesDataUnitOfWork]
Clock = Callable[[], datetime]
IdFactory = Callable[[], str]
